apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: weather-app
data:
  MONGO_URI: "mongodb://mongodb.infra.svc.cluster.local:27017/weather_db"
  KAFKA_BROKERS: "kafka.infra.svc.cluster.local:29092"
  KAFKA_LOGIN_TOPIC: "user-login-events"
  OTEL_SERVICE_NAME: "weather-backend-service"
  OTEL_TRACES_EXPORTER: "zipkin"
  OTEL_EXPORTER_ZIPKIN_ENDPOINT: "http://otel-collector.monitoring.svc.cluster.local:9411/api/v2/spans"
  OTEL_RESOURCE_ATTRIBUTES: "service.instance.id=backend-instance-1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: weather-app
  labels: { app: backend }
spec:
  replicas: 1
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
        - name: backend
          image: slayder2709/weather-backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: weather-app
spec:
  selector: { app: backend }
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
  type: NodePort