apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: weather-app
  labels: { app: nginx }
spec:
  replicas: 1
  selector:
    matchLabels: { app: nginx }
  template:
    metadata:
      labels: { app: nginx }
    spec:
      containers:
        - name: nginx
          image: slayder2709/weather-nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: weather-app
spec:
  selector: { app: nginx }
  type: NodePort
  ports:
    - port: 80
      targetPort: 80