apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywalking-oap
  namespace: monitoring
  labels: { app: skywalking-oap }
spec:
  replicas: 1
  selector:
    matchLabels: { app: skywalking-oap }
  template:
    metadata:
      labels: { app: skywalking-oap }
    spec:
      
      containers:
        - name: skywalking-oap
          image: apache/skywalking-oap-server:9.7.0
          ports:
            - containerPort: 12800
            - containerPort: 11800
            - containerPort: 1234
          env:
            - name: SW_STORAGE
              value: "h2"
            - name: SW_OTEL_RECEIVER
              value: "default"
            - name: SW_OTEL_RECEIVER
              value: "default"
            - name: SW_OTEL_RECEIVER_ENABLED_OTEL_METRICS_RULES
              value: "oap,mongodb/mongodb-cluster,mongodb/mongodb-node"
            - name: SW_TELEMETRY
              value: "prometheus"
            - name: SW_TELEMETRY_PROMETHEUS_HOST
              value: "0.0.0.0"
            - name: SW_TELEMETRY_PROMETHEUS_PORT
              value: "1234"
          readinessProbe:
            tcpSocket: { port: 11800 }
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          livenessProbe:
            tcpSocket: { port: 11800 }
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-oap
  namespace: monitoring
spec:
  selector: { app: skywalking-oap }
  ports:
    - name: rest
      port: 12800
      targetPort: 12800
    - name: grpc
      port: 11800
      targetPort: 11800
    - name: prometheus-port
      port: 1234
      targetPort: 1234
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywalking-ui
  namespace: monitoring
  labels: { app: skywalking-ui }
spec:
  replicas: 1
  selector:
    matchLabels: { app: skywalking-ui }
  template:
    metadata:
      labels: { app: skywalking-ui }
    spec:
      containers:
        - name: skywalking-ui
          image: apache/skywalking-ui:9.7.0
          ports:
            - containerPort: 8080
          env:
            - name: SW_OAP_ADDRESS
              value: "http://skywalking-oap:12800"
---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-ui
  namespace: monitoring
spec:
  selector: { app: skywalking-ui }
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31389
  type: NodePort
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skywalking-oap-k8s-metadata
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skywalking-oap-k8s-metadata
subjects:
  - kind: ServiceAccount
    name: default
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: skywalking-oap-k8s-metadata
  apiGroup: rbac.authorization.k8s.io